In [1]:
import numpy as np

In [2]:
x=np.random.rand(1,10)

In [3]:
y=np.random.randn(1,10)

In [4]:
z=np.random.randint(0,100,12)

In [5]:
z

array([66, 90, 85, 92, 61, 42, 94, 96, 51,  5, 18, 20])

In [6]:
x

array([[0.65960356, 0.23567445, 0.85707255, 0.62511951, 0.76568045,
        0.75720207, 0.4087841 , 0.87064581, 0.24268958, 0.3011871 ]])

In [7]:
y

array([[ 0.73467896, -1.23561121,  1.26551581, -0.92989744,  0.09364039,
         0.16392113, -1.20030359,  1.05709326,  1.18996205, -1.96730492]])

In [8]:
np.max(z)

96

In [9]:
np.min(z)

5

In [10]:
np.mean(z)

60.0

In [11]:
z

array([66, 90, 85, 92, 61, 42, 94, 96, 51,  5, 18, 20])

In [12]:
numbers=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [13]:
numbers

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
numbers.shape

(3, 4)

In [15]:
numbers.reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
numbers.reshape((12,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [17]:
np.sqrt(numbers)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [18]:
np.sin(numbers)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111, -0.99999021, -0.53657292]])

In [19]:
np.power(numbers,2)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]], dtype=int32)

In [20]:
a = np.arange(20).reshape(4, 5)

In [21]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
type(a)

numpy.ndarray

In [23]:
np.linspace(0, 10, num=5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
ones=np.ones((3,4))

In [25]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
zeros=np.zeros((5,5))

In [27]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])